export { default as HomeLayout } from './HomeLayout';
export { default as CheckoutPage } from './CheckoutPage';
export { default as Success } from './Success';
export { default as Landing } from './Landing';
export { default as CartPage } from './CartPage';
export { default as ErrorPage } from './ErrorPage';
export { default as PaymentPage } from './PaymentPage';
export { default as ProductPage } from './ProductPage';
export { default as SinglePage } from './SinglePage';
